import {defineConfig} from '@pandacss/dev';
import baseConfig from './panda.config';

/**
 * Panda config for the docs site's stylesheet (site/src/styles/panda.css,
 * generated by the site's pre-scripts). Same theme as the library, with two
 * differences: story files' css() calls and the site's own sources are
 * scanned, and the element resets are scoped to the live-demo boxes so they
 * cannot leak into Starlight's UI or prose.
 */
export default defineConfig({
  ...baseConfig,
  preflight: {scope: '[data-component-preview]'},
  include: ['./src/**/*.{ts,tsx}', './site/src/**/*.{ts,tsx,astro,mdx}'],
});
