// Generated by scripts/generate-version.mjs from package.json — do not edit.

/**
 * The silver-ui package version, e.g. `'1.10.10'`. Matches the published
 * npm version of the running code. Log or render it in an app to verify which
 * silver-ui build a deployment is actually using.
 */
export const version = '1.10.10';
