/**
 * generate-version.mjs — regenerates src/utils/version.ts from package.json.
 *
 * Runs as the npm `version` lifecycle script, which fires after `npm version`
 * bumps package.json and before it creates the release commit, so the staged
 * file lands in the same commit as the bump. A unit test
 * (src/utils/version.test.ts) fails the build if the two ever drift apart.
 */
import {readFileSync, writeFileSync} from 'node:fs';
import {URL} from 'node:url';

const packageJsonUrl = new URL('../package.json', import.meta.url);
const versionFileUrl = new URL('../src/utils/version.ts', import.meta.url);

const {version} = JSON.parse(readFileSync(packageJsonUrl, 'utf8'));

if (typeof version !== 'string' || version.length === 0) {
  throw new Error('package.json has no version to generate from');
}

writeFileSync(
  versionFileUrl,
  `// Generated by scripts/generate-version.mjs from package.json — do not edit.

/**
 * The silver-ui package version, e.g. \`'${version}'\`. Matches the published
 * npm version of the running code. Log or render it in an app to verify which
 * silver-ui build a deployment is actually using.
 */
export const version = '${version}';
`,
);
